### ISSUE TITLE
Log HomeKit Commands

### ISSUE THREAD

**Issue by cjsfj** [dustindclark/homebridge-pentair-intellicenter#3]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Add log entries that show when HomeKit commands are executed (i.e. "Pool Switch Turned On" or something) -- Or at least a mode to enable a debug log for these actions

**Describe alternatives you've considered:**
n/a

**Additional context:**
It would just be nice to use as a debugging or validation step - when a switch is turned on in the home app to see the resulting acknowledgement by the plugin in the log.

**Comment by dustindclark** [comment]
Fixed in 1.0.27.

**Comment by cjsfj** [comment]
Confirmed. This is great. Thank you.
