### ISSUE TITLE
Lowest Displayed Temperature (12.777C / 55F)

### ISSUE THREAD

**Issue by bverenkoff** [dustindclark/homebridge-pentair-intellicenter#60]
[11/18/2022, 7:18:23 AM] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 10.777777777777777 exceeded minimum of 12.777777777777777. See https://homebridge.io/w/JtMGR for more info.

Any chance we can have the legal limit show higher than 55F just to monitor temperature? Perhaps this is a thermostat minimum for Apple?

**Comment by dustindclark** [comment]
Upgrade to the latest version. This was recently fixed.DustinSent from my iPhoneOn Nov 18, 2022, at 5:20 AM, bverenkoff ***@***.***> wrote:﻿
[11/18/2022, 7:18:23 AM] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 10.777777777777777 exceeded minimum of 12.777777777777777. See https://homebridge.io/w/JtMGR for more info.
Any chance we can have the legal limit show higher than 55F just to monitor temperature? Perhaps this is a thermostat minimum for Apple?

**Comment by dustindclark** [comment]
The constraints were removed. Homebridge or HomeKit must apply a default. I suppose I can reapply a very loose constraint. Will try to look at this next week.{DustinSent from my iPhoneOn Nov 18, 2022, at 2:39 PM, bverenkoff ***@***.***> wrote:﻿
I am running 2.0.8. I upgraded like a week ago.

**Comment by bverenkoff** [comment]
Thanks, love this plug-in. So much better than using the native Pentair app!

Cheers,
Brian

On Nov 18, 2022, at 19:53, Dustin Clark ***@***.***> wrote:


The constraints were removed. Homebridge or HomeKit must apply a default. I suppose I can reapply a very loose constraint. Will try to look at this next week.{DustinSent from my iPhoneOn Nov 18, 2022, at 2:39 PM, bverenkoff ***@***.***> wrote:﻿
I am running 2.0.8. I upgraded like a week ago.

**Comment by dustindclark** [comment]
Can you try again in 2.0.9?

**Comment by bverenkoff** [comment]
Yeah, it works now. Thanks so much!

Sent from my iPhone

On Nov 20, 2022, at 10:35, Dustin Clark ***@***.***> wrote:

﻿

Can you try again in 2.0.9?

**Comment by bverenkoff** [comment]
[image]

Sent from my iPhone

On Nov 20, 2022, at 10:35, Dustin Clark ***@***.***> wrote:

﻿

Can you try again in 2.0.9?

**Comment by dustindclark** [comment]
Great, thanks!
