### ISSUE TITLE
Data Not Dynamic/Mirroring

### ISSUE THREAD

**Issue by gramster1** [dustindclark/homebridge-pentair-intellicenter#8]
When selecting either the "Pool" or "Spa" heater, I am able to successfully activate the temp and heater switch, however after settings are saved the tile shows gray and inactive in HomeKit, the settings stay on the IntelliCenter side. I am required to re trigger the switches and heater tiles for IntelliCenter to reflect my intended state. Additionally there are two switches, one labeled "Spa" and one labeled "Pool. Are these needed? It seems after they are turned on they immediately turn off.

It also seems the "heating to" temps stay the same as well as the current temp label stuck at 32.

I am running firmware 1.064 for IntelliCenter, and 1.4.1 for Homebridge.

**Comment by bverenkoff** [comment]
Same issues here, 1.5.0 on Homebridge and 1.064 on IntelliCenter. Temps are always stuck on 32F and things can get out of sync.

**Comment by bverenkoff** [comment]
I reboot fixed my issues. Temperature is now reading and things seem to be sync'ing OK. In HomeKit, I wish there were actual heater controls in the heat tab.

**Comment by dustindclark** [comment]
You should be able to control your heater. Do you not see this button?

![91A492E6-7F1C-48CC-BF0C-6D98367D46C7](https://user-images.githubusercontent.com/3819936/192648088-9ad479ad-a8ce-439f-ba29-38d6e3b505bc.jpeg)

Once the heater is on, you can adjust temp:

![29E3C9E4-EF0C-483D-AC16-D10024C25BA0](https://user-images.githubusercontent.com/3819936/192648167-0b0724a3-766d-48cf-aab9-a991e3b54c98.png)

**Comment by paulm** [comment]
I was having the same issue but uninstalled prior to seeing the idea to reboot. I will reinstall, reboot and try again

**Comment by bverenkoff** [comment]
Yea, I figured that out. It works, but I was hoping I could adjust the temperature prior to turning it on or off similar to my other thermostats.

Here’s my home thermostat which is also Homebridged for example.
[image0.png]

Also, on the main Apple display it appears the heaters are on when they aren’t as it always says “Heating to XX” even when off. It’s actually only on if it’s orange.

[image]

Anyways, it’s all working now.

Thanks,
Brian

Sent from my iPhone

On Sep 27, 2022, at 17:23, Dustin Clark ***@***.***> wrote:

﻿

You should be able to control your heater. Do you not see this button?

[91A492E6-7F1C-48CC-BF0C-6D98367D46C7]<https://user-images.githubusercontent.com/3819936/192648088-9ad479ad-a8ce-439f-ba29-38d6e3b505bc.jpeg>

Once the heater is on, you can adjust temp:

[29E3C9E4-EF0C-483D-AC16-D10024C25BA0]<https://user-images.githubusercontent.com/3819936/192648167-0b0724a3-766d-48cf-aab9-a991e3b54c98.png>

**Comment by dustindclark** [comment]
If your heater is turned on, you can control temperature. That said, I can only test with my setup. Do you see this button?DustinSent from my iPhoneOn Sep 27, 2022, at 4:31 PM, bverenkoff ***@***.***> wrote:﻿
I reboot fixed my issues. Temperature is now reading and things seem to be sync'ing OK. In HomeKit, I wish there were actual heater controls in the heat tab.

**Comment by dustindclark** [comment]
> Yea, I figured that out. It works, but I was hoping I could adjust the temperature prior to turning it on or off similar to my other thermostats. Here’s my home thermostat which is also Homebridged for example. [image0.png] Also, on the main Apple display it appears the heaters are on when they aren’t as it always says “Heating to XX” even when off. It’s actually only on if it’s orange. [image] Anyways, it’s all working now. Thanks, Brian
> […](#)

Not being able to control temp while off is a HomeKit limitations. All thermostats behave that way.

The other issue showing `Heating to` is a known issue  with a couple of my plugins that I haven't had time to address. Not sure if Pentair exposes whether or not the heater is running though, so we may have to live with it. If you want to open a separate issue for that, I'll look into it.

Closing this one since it's no longer a problem.
